base_domain_keywords = {
  'health_and_fitness': {
    'physical_health': [
      'hiit', 'abdominal exercises', 'aerobic fitness', 'archery', 'athlete',
      'athletic training', 'badminton', 'baseball', 'basketball', 'bench press',
      'bodyweight circuit', 'bodyweight training', 'bouldering', 'boxing', 'build muscle',
      'calisthenics', 'cardio', 'cardio challenge', 'cardio sessions', 'championship',
      'climbing', 'club sports', 'coach', 'competitive sports', 'conditioning',
      'core', 'core strengthening', 'core workout', 'cricket', 'cycling',
      'daily run habit', 'endurance training', 'equestrian', 'equipment', 'fencing',
      'fitness competition', 'fitness progress tracking', 'fitness streak', 'fitness tracker', 'flexibility',
      'football', 'form', 'functional fitness', 'game strategy', 'get lean',
      'golf', 'gym', 'gymnastics', 'handball', 'heart rate',
      'hockey', 'home workout', 'home workout plan', 'hypertrophy', 'improve endurance',
      'individual sports', 'jump rope', 'jump rope routine', 'lacrosse', 'league',
      'lean muscle', 'martial arts', 'match', 'match prep', 'mobility',
      'pilates', 'pilates class', 'ping pong', 'pullup training', 'pushup progression',
      'referee', 'reps', 'rugby', 'run', 'running',
      'score', 'sets', 'skateboarding', 'skiing', 'soccer',
      'sports league', 'sports practice', 'sportsmanship', 'sprinting', 'stamina building',
      'step count', 'step goal', 'step goal streak', 'steps', 'strength training',
      'stretch', 'stretch routine', 'stretching', 'swimming', 'team captain',
      'team sports', 'technique', 'tennis', 'tournament', 'track and field',
      'varsity team', 'volleyball', 'walk', 'walk 10k steps', 'walking',
      'walking routine', 'weight gain goal', 'weight loss goal', 'weight target', 'workout',
      'wrestling'
    ],
    'nutrition_and_sleep': [
      'alarm avoidance', 'baking', 'bedtime', 'bedtime alarm', 'bedtime consistency',
      'bedtime routine', 'blue light exposure', 'bmi', 'body fat', 'body fat percentage',
      'bulking', 'caffeine cut-off', 'calorie deficit', 'calories', 'chef tips',
      'circadian rhythm', 'clean eating', 'comfort food', 'consistent bedtime', 'cooking',
      'culinary arts', 'cut processed sugar', 'cutting', 'daily calorie log', 'deep sleep tracking',
      'dessert', 'diet', 'drink water', 'early wake habit', 'eating',
      'eating schedule', 'eating window', 'fix sleep schedule', 'grilling', 'healthy eating',
      'healthy snacking', 'hydration', 'hydration habit', 'hydration reminder', 'hydration tracking',
      'improve sleep quality', 'intentional eating', 'intermittent fasting', 'international cuisine', 'intuitive eating',
      'kitchen gadget', 'lean mass', 'macro tracking', 'macronutrient balance', 'macros',
      'meal plan', 'meal prep', 'meal timing', 'melatonin cycle', 'metabolism',
      'minerals', 'morning sunlight', 'nap routine', 'natural wakeup', 'no junk food streak',
      'no screens before bed', 'no takeout goal', 'nutrient density', 'nutrition', 'organic eating habit',
      'portion control', 'processed food avoidance', 'processed food reduction', 'protein', 'protein goal',
      'protein intake', 'protein target', 'recipe', 'sleep', 'sleep before midnight',
      'sleep consistency', 'sleep duration', 'sleep hygiene', 'sleep hygiene practice', 'sleep latency',
      'sleep quality', 'sleep rituals', 'sleep routine', 'sleep schedule', 'sleep tracker',
      'sleep tracking', 'sugar detox', 'sugar reduction', 'supplement routine', 'supplements',
      'track macros', 'tracking macros', 'vegan cooking', 'vegetarian meal', 'vitamins',
      'wake', 'wake up at', 'wake up early', 'water', 'water intake goal',
      'weight management', 'white noise', 'whole foods', 'wind down routine'
    ],
    'mental_wellness': [
      'anxiety', 'anxiety journaling', 'anxiety management', 'anxiety recovery', 'body positivity',
      'body scan', 'breathing exercises', 'burnout check-in', 'burnout prevention', 'cognitive reframing',
      'content consumption control', 'counseling', 'deep journaling', 'depression', 'digital detox',
      'dopamine detox', 'emotional journaling', 'emotional regulation', 'emotional release', 'emotional wellbeing',
      'energy flow', 'fulfillment', 'gratitude journal', 'gratitude prompts', 'grounding techniques',
      'guided meditation', 'happiness', 'journal', 'journaling', 'journaling prompts',
      'me time', 'me time practice', 'meditation', 'mental clarity', 'mental health',
      'mental health break', 'mental reset', 'mind-body connection', 'mindful habits', 'mindfulness',
      'mindless scrolling detox', 'mindless scrolling limit', 'mindless scrolling reduction', 'motivation', 'movement therapy',
      'no social media', 'no social media challenge', 'phone-free time', 'pilates', 'prayer',
      'prayer routine', 'psychiatry', 'psychology', 'qigong', 'relaxation',
      'resilience', 'restorative yoga', 'screen time', 'screen time limit', 'self care',
      'self relfection', 'self-acceptance', 'self-acceptance work', 'self-esteem building', 'self-kindness',
      'self-reflection', 'social media fast', 'somatic practice', 'sound bath', 'stress',
      'tai chi', 'therapy', 'therapy goals', 'therapy tools', 'yin yoga',
      'yoga', 'zen practice'
    ]
  },
  'technology_and_computing': {
    'software_and_web_dev': [
      '.net', 'api development', 'dsa revision', 'a/b testing', 'accessibility',
      'accessibility testing', 'adobe xd', 'agile', 'agile sprint', 'android',
      'angular', 'api', 'asp.net', 'astro', 'automating',
      'automation', 'backend development', 'backend project', 'bash', 'bootstrap',
      'branch', 'build landing page', 'build mvp', 'bulma', 'c',
      'c#', 'c++', 'c++ practice', 'c++ revision', 'chakra ui',
      'clean code practice', 'code review', 'coding', 'coding habit', 'coding streak',
      'color palette', 'commit', 'competitive programming', 'compiler', 'css',
      'css framework', 'css styling', 'data structure mastery', 'debugging', 'debugging challenge',
      'deployment', 'design', 'design feedback', 'design feedback loop', 'design iteration',
      'design system', 'dev streak', 'devtools', 'django', 'dotnet',
      'electron', 'express', 'fastapi', 'figma', 'flask',
      'flutter', 'foundation', 'frontend', 'frontend build', 'frontend course',
      'frontend design', 'frontend development', 'frontend projects', 'full stack', 'git',
      'git commits streak', 'go', 'graphql', 'hackathon', 'hackathon project',
      'html', 'html portfolio', 'integration testing', 'interaction design', 'ionic',
      'ios', 'java', 'java learning', 'javascript', 'js',
      'kotlin', 'laravel', 'leetcode grind', 'leetcode practice', 'linting',
      'material ui', 'merge', 'metlab training', 'mobile app', 'mobile-friendly site',
      'modular code', 'mvp goal', 'nestjs', 'nextjs', 'node',
      'node.js', 'nuxt', 'optimizing systems', 'pair programming', 'persona mapping',
      'php', 'portfolio projects', 'programming', 'progressive web app', 'prototype',
      'pull request', 'python', 'qt', 'r', 'rails',
      'react', 'react native', 'react project', 'remix', 'repository',
      'responsive', 'responsive design', 'responsive layout', 'responsive ui', 'rest',
      'ruby', 'rust', 'scrum', 'shell', 'solidjs',
      'solidworks', 'spring', 'sprint', 'sql', 'svelte',
      'sveltekit', 'swift', 'system design', 'tailwind', 'tailwind css',
      'technical interview prep', 'testing', 'tkinter', 'ts', 'typescript',
      'typography', 'ui', 'ui audit', 'ui component design', 'ui design',
      'ui mockup', 'unit test coverage', 'unit testing', 'usability testing', 'user experience',
      'user interface', 'user journey', 'ux', 'ux writing', 'version control',
      'vue', 'web components', 'web deployment', 'web dev bootcamp', 'wireframe',
      'writing algorithms', 'wxpython', 'xamarin'
    ],
    'emerging_tech_and_ai': [
      '3d environment', '3d immersion', '3d modeling', 'ai ethics', 'animation',
      'ar filter', 'asset import', 'augmented interface', 'augmented reality', 'bitcoin',
      'block explorer', 'blockchain', 'blockchain node', 'character design', 'chatbot',
      'computer vision', 'consensus algorithm', 'construct', 'crypto wallet', 'cryptocurrency',
      'dapp development', 'data analysis', 'data labeling', 'data visualization', 'data wrangling',
      'dataset cleaning', 'decentralized app', 'deep learning', 'defi', 'defold',
      'embedding space', 'entanglement', 'ethereum', 'exchange', 'eye tracking',
      'feature engineering', 'game ui', 'game balance', 'game development', 'game engine',
      'game jam', 'game loop', 'game maker', 'game ui', 'gas fee',
      'gesture control', 'gesture interface', 'godot', 'grover search', 'haptic feedback',
      'headset', 'hyperparameter tuning', 'immersive experience', 'in-game economy', 'layer 2',
      'level design', 'level scripting', 'libgdx', 'love2d', 'machine learning',
      'mining', 'mixed reality', 'mixed reality app', 'ml pipeline', 'model deployment',
      'model evaluation', 'model training', 'monogame', 'multiplayer setup', 'natural language processing',
      'neural networks', 'nft', 'nlp', 'physics engine', 'playtesting',
      'predictive analytics', 'private key', 'public key', 'pygame', 'pyglet',
      'qiskit', 'quantum algorithm', 'quantum architecture', 'quantum circuit', 'quantum compiler',
      'quantum computing', 'quantum decoherence', 'quantum error correction', 'quantum gate', 'quantum hardware',
      'quantum noise', 'quantum runtime', 'quantum sdk', 'quantum simulator', 'quantum supremacy',
      'qubit', 'raylib', 'recommendation system', 'rpg maker', 'shader',
      'shor algorithm', 'smart contract audit', 'smart contracts', 'spatial computing', 'spatial mapping',
      'sprite animation', 'staking', 'superposition', 'text generation', 'token',
      'tokenomics', 'training data', 'unity', 'unreal engine', 'virtual reality',
      'vr app', 'vr prototype', 'vr training', 'wallet', 'xr platform',
      'yield farming'
    ],
    'infrastructure_and_security': [
      'access control', 'actuator', 'arduino', 'authentication', 'aws',
      'azure', 'bluetooth', 'ci cd', 'ci pipeline', 'cloud computing',
      'cloud function', 'cluster management', 'continuous deployment', 'continuous integration', 'cyber hygiene',
      'cybersecurity', 'data breach', 'data encryption', 'deployment script', 'devops',
      'devops automation', 'docker', 'embedded linux', 'embedded systems', 'encryption',
      'endpoint protection', 'ethical hacking', 'firewall', 'firmware', 'firmware update',
      'gcp', 'gpio', 'incident response', 'infrastructure as code', 'infrastructure monitoring',
      'iot analytics', 'iot devices', 'iot gateway', 'iot integration', 'iot platform',
      'iot protocol', 'kubernetes', 'load balancing', 'logging', 'logging system',
      'low power design', 'malware', 'microcontroller', 'monitoring', 'multi-cloud',
      'network security', 'password policy', 'penetration testing', 'penetration toolkit', 'phishing',
      'raspberry pi', 'real time', 'real-time data', 'risk assessment', 'scalability',
      'security audit', 'security patching', 'sensor', 'sensor fusion', 'serverless',
      'service mesh', 'social engineering', 'terraform', 'threat modeling', 'two factor',
      'vpn', 'vulnerability', 'wifi'
    ]
  },
  'creative_arts_and_hobbies': {
    'arts_and_creation': [
      '3d modeling', 'diy project', 'ae editing', 'analytics review', 'animation',
      'art', 'art challenge', 'art installation', 'art portfolio', 'art streak',
      'art technique', 'audio editing', 'band rehearsal', 'beading', 'blender practice',
      'blog', 'blogging', 'book club', 'camera work', 'caption editing',
      'carving', 'ceramics', 'channel growth', 'character design', 'cinematography',
      'composition challenge', 'composition work', 'concept art', 'concept art session', 'concert',
      'content ideas', 'content schedule', 'creative journaling', 'creative streak', 'creative writing',
      'crochet', 'daily blog entry', 'daily drawing habit', 'daily guitar practice', 'design',
      'digital art', 'djing', 'documentary', 'draw', 'drawing',
      'drums', 'editing', 'editing draft', 'editing workflow', 'embroidery',
      'engagement metrics', 'essay writing', 'exhibition', 'exhibition prep', 'figure drawing',
      'film production', 'gallery', 'graphic design', 'guitar', 'guitar practice',
      'handmade craft', 'illustration', 'illustration challenge', 'instrument', 'instrument mastery',
      'instrument practice', 'jam session', 'jewelry making', 'journal', 'journalism',
      'knitting', 'landscape photography', 'learn 3d modeling', 'lightroom', 'literature',
      'livestreaming', 'macro photography', 'mastering', 'metalwork', 'mixed media',
      'mixing', 'motion graphics', 'museum', 'music', 'music composition',
      'music portfolio', 'music production', 'music release', 'music release schedule', 'music theory',
      'music theory review', 'novel', 'novel progress tracking', 'novel writing', 'origami',
      'paint', 'painting', 'painting goal', 'painting practice', 'papercraft',
      'photo editing', 'photography', 'photoshop', 'piano', 'piano progression',
      'podcasting', 'poetry', 'portfolio review', 'portrait photography', 'pottery',
      'practice music', 'practice piano pieces', 'printmaking', 'proofreading', 'publish short story',
      'publishing', 'quilting', 'read', 'reading', 'record vocals',
      'recording sessions', 'scrapbooking', 'screenwriting', 'scriptwriting', 'scriptwriting session',
      'sculpture', 'sewing', 'short film', 'shorts production', 'singing',
      'sketch', 'sketch practice', 'sketching', 'sketching routine', 'social video',
      'song', 'song production', 'song production habit', 'songwriting', 'sound design',
      'story', 'story outlining', 'storyboarding', 'storytelling', 'studio setup',
      'style exploration', 'subscriber goal', 'subscriber milestone', 'thumbnail design', 'vfx',
      'video batching', 'video editing', 'video production', 'videography', 'violin',
      'vocal', 'vocal training', 'vocal warmup', 'voiceover script', 'weaving',
      'woodworking', 'write', 'write 200 words daily', 'writing', 'writing portfolio',
      'writing prompt response', 'youtube strategy'
    ],
    'performance_and_play': [
      'acting', 'ballet', 'board games', 'card games', 'character creation',
      'checkers', 'chess', 'circus arts', 'cosplay', 'costume design',
      'crossword', 'dance performance', 'dungeons and dragons', 'escape rooms', 'hip hop dance',
      'historical reenactment', 'improv', 'larp', 'magic tricks', 'puzzle solving',
      'roleplaying games', 'stage show', 'stand-up comedy', 'strategy games', 'sudoku',
      'tabletop rpg', 'theater'
    ],
    'collection_and_curation': [
      'action figures', 'antiques', 'autographs', 'coins', 'collectibles',
      'dioramas', 'memorabilia', 'miniatures painting', 'model building', 'stamps',
      'trading cards', 'vintage items'
    ]
  },
  'business_and_finance': {
    'personal_finance_and_investing': [
      '401k', 'accounting', 'appraisal', 'asset', 'auditing',
      'auto loan', 'balance sheet', 'bitcoin', 'brokerage', 'budget tracking',
      'budgeting', 'cap rate', 'capital', 'cash flow', 'checking account',
      'claim', 'closing costs', 'create budget plan', 'credit card', 'credit score',
      'crypto', 'crypto updates', 'debt', 'debt repayment', 'deductible',
      'diversification', 'dividend', 'emergency fund', 'equity', 'etf',
      'expense', 'expense reduction', 'financial alignment', 'financial goal', 'financial independence',
      'financial literacy goal', 'financial statement', 'forex', 'freelance earnings', 'fundamental analysis',
      'futures', 'health insurance', 'hoa fees', 'home loan', 'income statement',
      'insurance', 'interest rate', 'investing', 'investment', 'investment habit',
      'investment plan', 'investment property', 'investment tracking', 'ira', 'landlord',
      'learn forex', 'liability', 'loan', 'loss', 'market trend',
      'monitor portfolio', 'monthly expense', 'mortgage', 'mutual fund', 'net income',
      'net worth', 'option trading', 'passive income', 'personal budget', 'portfolio',
      'premium', 'profit', 'property', 'property management', 'real estate',
      'real estate agent', 'rental income', 'retirement planning', 'revenue', 'risk tolerance',
      'roi', 'savings account', 'savings target', 'short selling', 'side income',
      'spending habit', 'stock', 'stock market', 'stock market learning', 'stocks',
      'student loan', 'study investing basics', 'tax filing', 'tax return', 'technical analysis',
      'tenant', 'title insurance', 'track passive income', 'trading', 'valuation',
      'volatility', 'wealth building', 'zoning'
    ],
    'business_strategy': [
      'mvp development', 'accelerator', 'advertising', 'affiliate marketing', 'angel investor',
      'automation', 'branding', 'business launch', 'business model', 'campaign',
      'cap table', 'client acquisition', 'competitive analysis', 'compliance', 'content marketing',
      'conversion rate', 'corporate governance', 'customer discovery', 'customer feedback', 'customer retention',
      'demo day', 'dilution', 'email marketing', 'engagement rate', 'equity',
      'feature prioritization', 'founder', 'fundraising', 'funnel', 'growth hacking',
      'incubator', 'influencer marketing', 'intellectual property', 'iteration', 'kpi',
      'lead generation', 'lean startup', 'legal structure', 'logistics', 'market research',
      'market testing', 'marketing strategy', 'monetization', 'mvp', 'networking goals',
      'operations', 'paid ads', 'pitch deck', 'pitch practice', 'pivot',
      'pricing strategy', 'process improvement', 'procurement', 'product launch', 'product management',
      'product validation', 'project management', 'quality control', 'revenue stream', 'revenue target',
      'risk management', 'roadmap', 'scalability', 'seo', 'social media',
      'startup', 'startup funding', 'supply chain', 'target audience', 'term sheet',
      'traction', 'user persona', 'value proposition', 'vendor management', 'venture capital'
    ],
    'career_and_economics': [
      'apply for internships', 'build resume', 'career', 'career development', 'central bank',
      'cover letter', 'currency exchange', 'cv', 'economic indicator', 'economics',
      'employee benefits', 'fiscal policy', 'freelance', 'freelance portfolio', 'freelance work',
      'gdp', 'get job ready', 'inflation', 'interest rate', 'internship',
      'interview', 'interview practice', 'job', 'job application', 'job interview',
      'job search', 'leadership', 'macroeconomics', 'management', 'market structure',
      'mentorship', 'microeconomics', 'monetary policy', 'networking', 'online course completion',
      'performance review', 'personal brand growth', 'portfolio', 'portfolio polish', 'promotion',
      'recession', 'remote work', 'resume', 'resume building', 'salary negotiation',
      'search for a job', 'side job', 'strategic review', 'study for certifications', 'supply and demand',
      'team collaboration', 'trade balance', 'unemployment rate', 'workflow system', 'workplace culture'
    ]
  },
  'education_and_learning': {
    'academic_and_exam_prep': [
      'academic backlog', 'academic integrity', 'academic year', 'assignment', 'bachelor',
      'bibliography', 'certificate', 'chartered analyst', 'citation', 'class',
      'college', 'college entrance', 'course', 'course competion', 'critical thinking',
      'curriculum', 'degree', 'diploma', 'essay writing', 'exam',
      'exam mindset', 'exam preparation', 'exam strategy', 'exam streak', 'financial aid',
      'focused study block', 'formula memorization', 'gate exam', 'graduation', 'homework',
      'homework revision', 'intensive prep', 'internship', 'lab work', 'language study',
      'lecture', 'master', 'mcat', 'mcat plan', 'mcat prep',
      'mock drill', 'mock test', 'mock tests', 'note taking', 'past paper practice',
      'past papers', 'peer review', 'phd', 'prep', 'presentation',
      'problem solving', 'project', 'research paper', 'review', 'revision',
      'revision schedule', 'scholarship', 'school', 'semester', 'student',
      'study', 'study abroad', 'study marathon', 'study skills', 'study slots',
      'study tracker', 'studying', 'subject revision', 'teacher', 'test',
      'test strategies', 'time management', 'transcript', 'tuition', 'university'
    ],
    'language_and_communication': [
      'chinese characters', 'duolingo streak', 'french studies', 'japanese lessons', 'spanish immersion',
      'arabic', 'armenian', 'bengali', 'body language', 'chinese',
      'croatian', 'czech', 'debate', 'duolingo', 'dutch',
      'esperanto', 'estonian', 'filipino', 'finnish', 'french',
      'georgian', 'german', 'grammar', 'greek', 'hebrew',
      'hindi', 'hungarian', 'icelandic', 'indonesian', 'interview skills',
      'italian', 'japanese', 'korean', 'language', 'language exam prep',
      'language learning', 'language partner', 'latvian', 'listening skills', 'malayalam',
      'mongolian', 'nonverbal communication', 'norwegian', 'persian', 'polish',
      'portuguese', 'pronunciation', 'pronunciation practice', 'public speaking', 'punjabi',
      'reading comprehension', 'rhetoric', 'romanian', 'russian', 'serbian',
      'slovak', 'slovenian', 'spanish', 'storytelling', 'storytellinggerman practice',
      'swahili', 'swedish', 'tagalog', 'tamil', 'telugu',
      'thai', 'turkish', 'ukrainian', 'urdu', 'verbal communication',
      'vietnamese', 'vocabulary', 'vocabulary building', 'writing skills'
    ],
    'personal_growth': [
      'assessment', 'blended learning', 'burnout awareness', 'burnout prevention', 'confidence',
      'consistency', 'consistency tracker', 'continuing education', 'course module', 'discipline',
      'dompamine detox', 'e-learning', 'emotional intelligence', 'flipped classroom', 'focus',
      'glow up', 'glow up goal', 'goal alignement', 'goal setting', 'grading system',
      'gratitude', 'growth focus', 'growth mindset', 'habit reset', 'habit tracking',
      'intention setting', 'interactive learning', 'journaling', 'knowledge retention', 'learning platform',
      'lesson plan', 'limit screen time', 'me time', 'meditation', 'mindfulness',
      'mindset', 'mooc', 'morning mindset', 'motivation', 'nofap',
      'online learning', 'personal development', 'productivity', 'professional training', 'quiz',
      'reflection', 'resilience', 'resilience training', 'routine', 'screen time limit',
      'screen time reduction', 'self awareness', 'self care', 'self discipline plan', 'self esteem',
      'self improvement', 'skill development', 'time management', 'video tutorial', 'webinar',
      'workshop'
    ]
  },
  'lifestyle_community_and_adventure': {
    'home_and_personal_life': [
      'appliances', 'baby care', 'bathroom cleaning', 'bathroom cleaning goal', 'celebrity lifestyle',
      'child development', 'clean kitchen daily', 'cleaning', 'cleaning tips', 'cook',
      'cooking', 'daily chores', 'declutter', 'declutter closet', 'decluttering',
      'designer item', 'digital cleanup', 'digital decluttering', 'education tools', 'exotic travel',
      'face mask session', 'family activity', 'family travel', 'fashion', 'fashion accessory',
      'fashion style', 'fine dining', 'fragrance', 'fragrance testing', 'furniture',
      'gardening', 'grooming', 'grooming routine', 'grooming streak', 'hair care routine',
      'haircare', 'high-end fashion', 'home decor', 'home improvement', 'home maintenance',
      'home schooling', 'housekeeping', 'housework', 'houswork', 'interior design',
      'kitchen', 'luxury brand', 'luxury car', 'makeup tips', 'meal cleanup',
      'minimalism', 'morning cleaning habit', 'nighttime skincare', 'organization', 'organize room',
      'outfit ideas', 'outfit tracking', 'parent support', 'parenting tips', 'personal grooming',
      'personal style expression', 'real estate luxury', 'seasonal trends', 'skincare', 'skincare goal',
      'skincare routine', 'streetwear', 'style', 'style upgrade', 'teen parenting',
      'tidy', 'tiny home', 'wardrobe organization', 'watch collection', 'weekly room reset',
      'work life balance', 'yacht'
    ],
    'travel_and_adventure': [
      'adventure sports', 'aviation hobby', 'backpacking', 'backpacking prep', 'base jumping',
      'biking', 'birdwatching', 'boating', 'bungee jumping', 'camping',
      'car maintenance', 'caving', 'climbing', 'cultural experience', 'cultural immersion',
      'destination research', 'digital nomad', 'driving tips', 'fishing', 'flight booking',
      'hiking', 'hotel stay', 'itinerary planning', 'kayaking', 'language immersion',
      'marine navigation', 'motocross', 'motorcycle travel', 'mountain walk', 'mountaineering',
      'national park', 'nature photography', 'off roading', 'paragliding', 'private pilot',
      'recreational vehicle', 'road trip', 'road trip gear', 'rock climbing', 'sailing',
      'scuba diving', 'skydiving', 'snowboarding', 'stargazing', 'surfing',
      'tourism', 'trail walking', 'travel blog', 'travel gear', 'travel guide',
      'travel planning', 'travel savings', 'travel vlogging', 'vacation', 'walk in nature',
      'whitewater rafting', 'wildlife exploration', 'yachting'
    ],
    'social_and_community': [
      'anniversary planning', 'bond with sibling', 'carbon footprint', 'celebration ideas', 'charity event',
      'civic engagement', 'climate change', 'communication skills', 'community service', 'composting',
      'conflict resolution', 'connect', 'dating advice', 'disaster relief', 'eco friendly',
      'environmental activism', 'family', 'family time priority', 'friend check-in', 'friend check-in goal',
      'friends', 'friendship', 'fundraising', 'gift giving', 'green energy',
      'improve social circle', 'intentional connection', 'make a new friend', 'make friends', 'marriage tips',
      'meaningful conversations', 'meet people', 'nonprofit work', 'public service', 'recycling',
      'relationship health', 'social activity', 'social battery management', 'social circle improvement', 'social etiquette',
      'social impact', 'social life', 'spend time with family', 'sustainable living', 'urban gardening',
      'volunteer opportunity', 'water conservation', 'weekly catch-up', 'weekly hangout', 'youth mentoring',
      'zero waste'
    ]
  },
  'science_and_research': {
    'scientific_fields': [
      'aerospace engineering', 'anthropology', 'archaeology', 'astronautics', 'astronomy',
      'astrophysics', 'bioinformatics', 'biology', 'biomedical engineering', 'biotechnology',
      'carbon nanotubes', 'cell biology', 'chemical engineering', 'chemistry', 'civil engineering',
      'climatology', 'clinical trials', 'diagnostic tools', 'ecology', 'electrical engineering',
      'energy systems', 'environmental engineering', 'genetics', 'genomics', 'geology',
      'graphene research', 'healthtech innovation', 'linguistics', 'mars mission', 'materials science',
      'mathematics', 'mechanical engineering', 'meteorology', 'microbiology', 'molecular biology',
      'molecular engineering', 'nanoengineering', 'nanomaterials', 'nanotechnology', 'neuroscience',
      'nuclear engineering', 'oceanography', 'orbital mechanics', 'paleontology', 'pharmaceutical research',
      'physics', 'planetary science', 'psychology', 'quantum materials', 'robotics research',
      'rocket propulsion', 'satellite technology', 'semiconductor research', 'sociology', 'space exploration',
      'space station', 'statistics', 'surface science', 'systems engineering', 'telescope observation',
      'vaccine development', 'virology'
    ],
    'research_process_and_tools': [
      'stem outreach', 'academic conference', 'data collection', 'experimental design', 'field study',
      'funding proposal', 'government lab', 'grant writing', 'hypothesis testing', 'industrial r&d',
      'lab technician', 'laboratory work', 'literature review', 'peer review', 'postdoctoral fellow',
      'principal investigator', 'research assistant', 'research ethics', 'research institute', 'research paper',
      'researcher', 'sciece interest', 'science educator', 'scientific method', 'scientific publication',
      'scientist', 'think tank', 'university lab'
    ]
  }
}
